Implementação Loggi
GabrielRF/RastreioBot pull request #138
Opened 2021-10-30 12:49 UTC by fbidu

Olá gente! Primeira contribuição aqui

Bem, eu comecei o trabalho na issue sobre a Loggi, #45. Infelizmente, eu não tô conseguindo criar uma conta no ambiente de staging deles, me parece fora do ar.

Enquanto comecei a implementar, li a documentação e encontrei:

> Para realizar a integração o cliente necessita ter uma conta Pessoa Jurídica ou o cadastro necessita ser do tipo CorporateUser. Caso o mesmo tente realizar a integração com uma conta de Pessoa Física, será retornado o erro “Forbidden. User should be a corporate user to access”.

Isso me faz pensar que a API seja limitada a pessoas que _enviam_ pacotes e não para que um cliente final que está aguardando um pacote consiga acompanhar o status. Como eu não estou aguardando um pacote da Loggi no momento e sem acesso ao ambiente de staging, não consigo testar essa hipótese :(

De qualquer forma, vou deixar o início da minha implementação aqui. Depois tento acessar staging de novo e ver se é possível ou não escrever o acesso do cliente

2021-10-30 13:17 UTC, rougeth commented
Boa @fbidu! Minha impressão é a mesma que a sua, e parece ser como a API do Mercado Livre. A API de rastreamento de pacotes funciona para quem os enviou, não é possível rastrear qualquer pacote dentro da plataforma.

2021-10-30 13:17 UTC, rougeth requested changes

2021-10-30 13:17 UTC, rougeth commented on apis/apiloggi.py
> +final_codes = {int(x) for x in config["LOGGI"]["final_codes"].split(", ")}
```suggestion
final_codes = {int(x) for x in config["LOGGI"]["final_codes"].split(",").strip()}
```
Para evitar que a config quebre por falta de espaço.

2021-10-30 13:17 UTC, rougeth commented on apis/apiloggi.py
> +    if status_codes & final_codes:
Boa!

2021-10-30 13:17 UTC, rougeth commented on apis/apiloggi.py
> +    }
Conhece alguma lib que facilite montar/manter as queries graphql?

2021-10-30 13:54 UTC, fbidu commented on apis/apiloggi.py
> +final_codes = {int(x) for x in config["LOGGI"]["final_codes"].split(", ")}
ah, boa!

2021-10-30 13:54 UTC, fbidu commented on apis/apiloggi.py
> +    if status_codes & final_codes:
Valeu :D

2021-10-30 15:22 UTC, rougeth commented on apis/apiloggi.py
> +    }
Entendi, fica quase a mesma coisa né? Melhor deixa assim mesmo do que inserir mais uma dependência.

2021-10-30 15:23 UTC, rougeth commented
Só mais um comentário (desculpa não ter mandando na primeira revisão), você consegue criar alguns testes nesse PR?

2021-11-08 19:54 UTC, fbidu commented
@rougeth vou fechar porque de fato o acesso é só pra quem enviou :( Discuti isso com um colega que já criou integração assim. Se tiver outra estrategia que é ok pra esse projeto (web scraping?) me avisa que eu reabro e continuo!

2021-11-08 19:54 UTC, closed without merging

2021-11-08 23:16 UTC, rougeth commented
Valeu @fbidu

2023-02-10 01:10 UTC, leandrobattochio commented
Boa noite. Para realizar o rastreio de um pacote para um consumidor final, sem necessidade de conta com CNPJ é bem simples. Basta tentar fazer a solicitação de rastreio usando o site normal deles com o console do chrome aberto. São 4 requests GraphQL que são enviados, apenas com um cookie. Sem nenhuma autenticação. Se tiver interesse me avisa que te mando os esquemas mas não tem segredo.

2023-02-13 12:22 UTC, fbidu commented
@leandrobattochio obrigado pela info! Infelizmente eu n vou conseguir implementar algo assim por esses dias, mas se vc quiser assumir, pode continuar do trabalho que deixei aqui :D